base_dir: /mnt/md0/hkkang/QAGPT/
api_server:
    host: 0.0.0.0
    port: 5004
colbert:
    wiki2017: 
        base_dir: ckpts/colbert/enwiki-20171001/
        collection: collection.tsv
        index: index.2bit
    wiki2020:
        base_dir: ckpts/colbert/enwiki-20200801/
        collection: collection.tsv
        index: index.2bit
baleen:
    wiki2017: 
        base_dir: ckpts/baleen/enwiki-20171001/
        collection: collection.jsonl
        index: hotpotqa.index.2bit
        api_index_name: enwiki-20171001-abstract
    wiki2020: 
        base_dir: ckpts/baleen/enwiki-20200801/
        collection: collection.jsonl
        index: hotpotqa.index.2bit
        api_index_name: enwiki-20200801
    checkpoint:
        hotpotqa: 
            flipr: ckpts/baleen/hotpotqa.checkpoints-v1.0/flipr-v1.0.dnn
            L1: ckpts/baleen/hotpotqa.checkpoints-v1.0/condenserL1-v1.0.dnn
            L2: ckpts/baleen/hotpotqa.checkpoints-v1.0/condenserL2-v1.0.dnn
    experiment_dir: ckpts/baleen/saved_experiments
