base_dir: /mnt/md0/hkkang/QAGPT/
collection:
    wiki_2017: data/wiki/enwiki-20171001-colbert-collection.tsv
    wiki_2020: data/wiki/enwiki-20200801-colbert-collection.tsv
checkpoint:
    hotpotqa: 
        flipr: ckpts/baleen/hotpotqa.checkpoints-v1.0/flipr-v1.0.dnn
        L1: ckpts/baleen/hotpotqa.checkpoints-v1.0/condenserL1-v1.0.dnn
        L2: ckpts/baleen/hotpotqa.checkpoints-v1.0/condenserL2-v1.0.dnn
experiment_dir: ckpts/baleen/saved_experiments
index:
    wiki_2017: ckpts/baleen/indexes/wiki17.hotpotqa.2bit
    wiki_2020: ckpts/baleen/indexes/wiki20.hotpotqa.2bit