version: "3"

services:
    project101-server:
        image: hyukkyukang/baleen:latest
        container_name: baleen
        stdin_open: true
        tty: true
        network_mode: "host"
        volumes:
            - ./:/root/baleen
