version: "3"

services:
    Baleen:
        image: hyukkyukang/baleen:latest
        container_name: Baleen
        stdin_open: true
        tty: true
        network_mode: "host"
        volumes:
            - ./:/root/Baleen
            - /mnt/nvme0n1p1/hkkang/QAGPT/:/mnt/md0/hkkang/QAGPT/
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
